### ISSUE TITLE
blaze-markup-0.6.3.0 test suite failure

### ISSUE THREAD

**Issue by peti** [jaspervdj/blaze-markup#15]
Citing from http://hydra.cryp.to/build/538134/nixlog/7/raw:

    Running 1 test suites...
    Test suite blaze-markup-tests: RUNNING...
    Text.Blaze.Tests:
      left identity Monoid law: [Failed]
    *** Failed! Falsifiable (after 6 tests): 
    "<img id=\"g\195\175d\" name=\"\" class=\"\195\144\" id=\"&#39;Y\"><img><div class=\"f\195\141\195\190\">U</div>"
    (used seed -4141915000318621053)
      right identity Monoid law: [Failed]
    *** Failed! Falsifiable (after 4 tests): 
    "<br class=\"\"><table class=\"\194\177\"><div name=\"\194\156\" id=\"\195\156\" class=\"MwF\" name=\"\195\189\"><area></div></table>"
    (used seed 3769094616709931206)
      associativity Monoid law: [Failed]
    *** Failed! Falsifiable (after 4 tests): 
    "<img name=\"\195\191\" class=\"\" id=\"P\194\164\195\178\" class=\"\">"
    ""
    "<area id=\"\" id=\"\" name=\"R`\">"
    (used seed 9159315065659811936)
      mconcat Monoid law: [Failed]
    *** Failed! Falsifiable (after 4 tests): 
    ["<img class=\"v\" name=\"\194\146\">"]
    (used seed 4417847674701686653)
      identity Applicative law: [Failed]
    *** Failed! Falsifiable (after 5 tests): 
    "<area name=\"\194\132\" class=\"#\" name=\"7c\">"
    (used seed 1682729845193000793)
      post escaping characters: [OK, passed 100 tests]
      valid UTF-8: [OK, passed 100 tests]
      external </ sequence: [OK, passed 100 tests]
      well nested <>: [OK, passed 100 tests]
      unsafeByteString id: [OK, passed 100 tests]
      conditional attributes: [OK]
      contents 1: [OK]
      empty 1: [OK]
      empty 2: [OK]
      comment 1: [OK]

             Properties   Test Cases  Total       
     Passed  5            5           10          
     Failed  5            0           5           
     Total   10           5           15          
    Test suite blaze-markup-tests: FAIL

**Comment by RyanGlScott** [comment]
This is especially strange since the test suite passes with `blaze-builder-0.3.3.4`, but not with `blaze-builder-0.4.0.0`. Since `blaze-markup` isn't touching any of `blaze-builder`'s internals, the current package maintainer (@lpsmith) claims [this shouldn't happen](http://blog.melding-monads.com/2015/02/12/announcing-blaze-builder-0-4/). I'd file a bug report, but the [repo](https://github.com/lpsmith/blaze-builder) is a fork and has no issue tracker.

**Comment by lpsmith** [comment]
My apologies for not having the issue tracker enabled;  I just fixed that issue.

I'll also start looking into this issue.   Thanks!

**Comment by lpsmith** [comment]
My initial reaction is that something is not actually getting written to the buffer,  and those special characters you are seeing in the output are uninitialized memory.

**Comment by lpsmith** [comment]
Well, my initial reaction is wrong, as those special characters are generated by what I'm assuming is some instance of `Arbitrary`.

**Comment by lpsmith** [comment]
Ok,  I did track down one of the causes of failure with this test suite,  namely,   `fromHtmlEscapedString` in `0.4` strips out any ASCII nonprinting characters,  whereas the same function from `0.3` leaves them in.

e.g.  with blaze-builder-0.3.3.2

> toLazyByteString (fromHtmlEscapedString "\DEL<foobar>\STX")
"\DEL&lt;foobar&gt;\STX"

with blaze-builder-0.4.0.0

> B.toLazyByteString (B.fromHtmlEscapedString "\DEL<foobar>\STX")
"&lt;foobar&gt;"

**Comment by lpsmith** [comment]
Ok,  "fixing" that discrepancy does fix the test suite.

I'm not sure how I feel about making that change though.   I'll have to do some more research into HTML escaping.

**Comment by jaspervdj** [comment]
This has been fixed, the test suite now doesn't generate control characters (which it shouldn't anyway).
