### ISSUE TITLE
ToMarkup instances for Data.Text.Lazy.Builder

### ISSUE THREAD

**Issue by andrewthad** [jaspervdj/blaze-markup#24]
I have added this in https://github.com/jaspervdj/blaze-markup/pull/23

**Comment by andrewthad** [comment]
Also, to add a little context, the reason why I want a `ToHtml` instance for `Data.Text.Lazy.Builder` is because I occasionally end up with `Builder`s, and right now I would call `toHtml . Builder.toLazyText`. With this PR, I can call `toHtml` more directly.

**Comment by jaspervdj** [comment]
Thanks!
