### ISSUE TITLE
Failure with ApplicativeDo

### ISSUE THREAD

**Issue by TerrorJack** [jaspervdj/blaze-markup#27]
Example provided by @snoyberg :

```haskell
{-# LANGUAGE ApplicativeDo #-}
{-# LANGUAGE OverloadedStrings #-}

import Data.Text (Text)
import Text.Blaze
import Text.Blaze.Renderer.String

foo :: Markup -> Markup
foo title = do
    "hello "
    title
    "!"

main :: IO ()
main = print $ renderMarkup $ foo "world"
```

This can trigger  `Exception: Text.Blaze.Internal.MarkupM: invalid use of monadic bind`. Originally reported at yesodweb/shakespeare#204 .

**Comment by jaspervdj** [comment]
I fixed this in `blaze-markup-0.8.0.0`.

**Comment by dylex** [comment]
Just a reminder that PR #16 adds a working monad instance.

**Comment by jaspervdj** [comment]
@dylex Yeah I ended up using a similar approach which adds the value more cases than `Empty`, so we can always get a value.  Unfortunately I forgot about the PR so I did it independently of your (great) work.  Sorry!
