### ISSUE TITLE
Build error on GHC 8.4.1-alpha1 

### ISSUE THREAD

**Issue by asr** [jaspervdj/blaze-markup#33]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got an error which was fixed by PR #29. Since this PR was merged, could you make a new release, please?

Blocking https://github.com/agda/agda/issues/2878.

**Comment by jaspervdj** [comment]
Thanks for the heads up, released as `blaze-markup-0.8.1.0`.

**Comment by asr** [comment]
Thanks for releasing!
