### ISSUE TITLE
extract value a from MarkupM a

### ISSUE THREAD

**Issue by olafklinke** [jaspervdj/blaze-markup#36]
Although the `MarkupM` monad is usually used as `Markup = MarkupM ()`, it sometimes is handy to use it in a monad transformer stack. For example, code that builds Html and keeps track of internal references might be of type `StateT Reference MarkupM ()`. It seems to be impossible, however, to replace the MarkupM monad inside the stack with another monad, say `IO` when rendering the Html. The reason is that  there is currently no (exposed) way of extracting the `a` from some `MarkupM a` value. Hence please either expose the function `markupValue :: MarkupM a -> a` or generalize the renderer functions to work not only on `MarkupM ()` but on any `MarkupM a`.

**Comment by jaspervdj** [comment]
I've been in this scenario a few times, and I think what you really want is something like `WriterT Markup m a` or `StateT Markup m a`.  Does that make sense?

**Comment by olafklinke** [comment]
Indeed `WriterT Markup (State Reference) ()` did the trick for me. Issue solved, thanks for the hint. Basically all I had to do was replace `lift` by `tell` in the do-notation building the `Markup`. Just out of curiosity: Why is `Markup` equal to `m ()` for some monad `m`? Just so that one can use do-notation to construct complicated values?

**Comment by jaspervdj** [comment]
Yeah, the `Monad` instance is mostly there to hijack the `do`-notation syntax.

**Comment by olafklinke** [comment]
I realized something: The `MarkupM a` type is isomorphic to `Writer MarkupMonoid a` for a type `MarkupMonoid` that can be obtained by deleting the parameter `a` from all the constructors of `MarkupM a`. For every monoid `m` the type `Writer m` is a monad, and conversely, for every monad `m` the type `m ()` is a monoid with `mempty = return ()` and `mappend = (>>)`. Thus one can have do-notation for every monoid. 
A re-structuring of the library might have `type Markup = MarkupMonoid` and `type MarkupDo = Writer MarkupMonoid ()` and make the combinators for building `Markup` be of type `MarkupDo` to encourage usage of do-notation.
