### ISSUE TITLE
blaze-markup-0.8.2.2 doesn't allow base-4.13 (GHC-8.8)

### ISSUE THREAD

**Issue by phadej** [jaspervdj/blaze-markup#44]
blaze-markup-0.8.2.0 allows, so there are some install plans with GHC-8.8 though.

**Comment by RyanGlScott** [comment]
I think the title of this issue should mention GHC 8.8, not 8.0?

**Comment by phadej** [comment]
@RyanGlScott thanks

**Comment by RyanGlScott** [comment]
See #45 for a fix.
