### ISSUE TITLE
Make a revision on hackage (for GHC 9.0)

### ISSUE THREAD

**Issue by andreasabel** [jaspervdj/blaze-markup#55]
Please go to https://hackage.haskell.org/package/blaze-markup/maintain and revise the upper bounds:

- `base < 4.16` (see #53)
- `tasty < 1.5` (see #52)

Optionally, also revise `tested-with` (see #54).

There is a handy tool for making revisions: https://github.com/hackage-trustees/hackage-cli.
E.g. after merging #54, you could try
```
hackage-cli push-cabal --incr-rev  blaze-markup.cabal
```
(This previews the changes. The revision is only actually made if you also supply `--publish`.)

**Comment by jaspervdj** [comment]
Hey, I did a release just now, sorry for the delay!

**Comment by andreasabel** [comment]
> Hey, I did a release just now, sorry for the delay!

Thanks!

Btw, I just learned this recently, but the preferred way to change bounds is a _revision_ (with the same version number) rather than a _release_ (allocating a new number).  Making revisions instead of releases would make the hackage trustees @hvr happy.

If the changelog is accurate, many of these could have been revisions:

- 0.8.2.8 (2021-03-04)
    * Bump `base` upper bound to 4.16
    * Bump `tasty` upper bound to 1.5
    * Bump `bytestring` upper bound to 0.12

- 0.8.2.7 (2020-06-30)
    * Bump Cabal version lower bound to 1.10

- 0.8.2.6 (2020-06-30)
    * Bump `tasty` upper bound to 1.4

- 0.8.2.5 (2020-04-20)
    * Bump `base` upper bound to 4.15

- 0.8.2.4 (2020-03-29)
    * Bump `QuickCheck` upper bound to 2.15

- 0.8.2.3 (2019-10-02)
    * Bump `base` to 4.13
    * Bump `tasty` to 1.2
    * Bump `QuickCheck` to 2.13

- 0.8.2.2 (2018-09-25)
    * Bump `base` to 4.12
    * Bump `containers` to 0.6
    * Bump `tasty` to 1.1

- 0.8.2.1 (2018-04-09)
    * Bump `QuickCheck` dependency to allow 2.11
    * Bump `tasty` dependency to allow 1.0
    * Bump `tasty-hunit` dependency to allow 0.10
    * Bump `tasty-quickcheck` dependency to allow 0.10

(Maybe next time.)
